package views.contactsnavigator;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafas
 */

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.CardLayout;

import controllers.ContactController;
import models.Contact;
import utils.FindContact;
import views.addform.*;
import views.editform.EditForm;

public class ContactsNavigator extends javax.swing.JFrame {
  private static ContactController contactController = null;
  private static ArrayList<Contact> contacts;
  private static Contact selectedContact;
  private static int actualContactIndex = 0;

  private static CardLayout cardLayout = new CardLayout();

  /**
   * Creates new form Contacts
   */
  public ContactsNavigator() {
    try {
      contactController = new ContactController();
      contacts = contactController.getContactsInAlphabeticalOrder();
      selectedContact = contacts.get(0);
      actualContactIndex = 0;
      initComponents();
      displayContact();
      this.setLocationRelativeTo(null);
      ImageIcon icon = new ImageIcon("src/assets/icon.png");
      this.setIconImage(icon.getImage());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this,
          "Erro ao iniciar a aplicação. Verifique a conexão e tente novamente.",
          "Agenda", JOptionPane.ERROR_MESSAGE);
      System.err.println("Error: " + e);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    buttonGroup1 = new javax.swing.ButtonGroup();
    visualizer = new javax.swing.JPanel();
    btnAddContact = new javax.swing.JButton();
    lblContactName = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    cmbChangeContact = new javax.swing.JComboBox<>();
    jPanel3 = new javax.swing.JPanel();
    btnPrevious = new javax.swing.JButton();
    lblContactImage = new javax.swing.JLabel();
    btnNext = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    txtAddress = new javax.swing.JTextField();
    jPanel6 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    txtNeighborhood = new javax.swing.JTextField();
    jPanel8 = new javax.swing.JPanel();
    jLabel9 = new javax.swing.JLabel();
    txtState = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    txtCity = new javax.swing.JTextField();
    jPanel10 = new javax.swing.JPanel();
    jLabel12 = new javax.swing.JLabel();
    txtCellphone = new javax.swing.JTextField();
    jPanel9 = new javax.swing.JPanel();
    jLabel11 = new javax.swing.JLabel();
    txtEmail = new javax.swing.JTextField();
    jPanel11 = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    txtCpf = new javax.swing.JTextField();
    jPanel7 = new javax.swing.JPanel();
    btnEdit = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Agenda");
    setBackground(new java.awt.Color(255, 255, 255));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setLocation(new java.awt.Point(0, 0));
    setName("Application"); // NOI18N
    getContentPane().setLayout(new java.awt.CardLayout());

    visualizer.setBackground(new java.awt.Color(255, 255, 255));

    btnAddContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add-contact.png"))); // NOI18N
    btnAddContact.setBorder(null);
    btnAddContact.setBorderPainted(false);
    btnAddContact.setContentAreaFilled(false);
    btnAddContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAddContact.setName("btnAddContact"); // NOI18N
    btnAddContact.setPreferredSize(new java.awt.Dimension(50, 50));
    btnAddContact.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddContactActionPerformed(evt);
      }
    });

    lblContactName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lblContactName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblContactName.setName("lblContactName"); // NOI18N

    jPanel2.setBackground(visualizer.getBackground());
    jPanel2.setMaximumSize(new java.awt.Dimension(315, 42));
    jPanel2.setMinimumSize(new java.awt.Dimension(315, 42));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel1.setText("Lista de Contatos");

    cmbChangeContact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
    cmbChangeContact.setToolTipText("Contato");
    cmbChangeContact.setAutoscrolls(true);
    cmbChangeContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    cmbChangeContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cmbChangeContact.setOpaque(true);
    cmbChangeContact.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbChangeContactActionPerformed(evt);
      }
    });

    if (contacts.size() > 0) {
      for (Contact contact : contacts)
        cmbChangeContact.addItem(contact.getName());
    }

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbChangeContact, javax.swing.GroupLayout.PREFERRED_SIZE, 152,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbChangeContact, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel3.setLayout(new java.awt.GridBagLayout());

    btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/left-arrow.png"))); // NOI18N
    btnPrevious.setBorder(null);
    btnPrevious.setBorderPainted(false);
    btnPrevious.setContentAreaFilled(false);
    btnPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnPrevious.setName("btnAddContact"); // NOI18N
    btnPrevious.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPreviousActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
    jPanel3.add(btnPrevious, gridBagConstraints);

    lblContactImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblContactImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/contact.png"))); // NOI18N
    lblContactImage.setName("lblContactImage"); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.weightx = 1.0;
    jPanel3.add(lblContactImage, gridBagConstraints);

    btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/right-arrow.png"))); // NOI18N
    btnNext.setBorder(null);
    btnNext.setBorderPainted(false);
    btnNext.setContentAreaFilled(false);
    btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnNext.setMaximumSize(new java.awt.Dimension(32, 32));
    btnNext.setMinimumSize(new java.awt.Dimension(32, 32));
    btnNext.setName("btnAddContact"); // NOI18N
    btnNext.setRequestFocusEnabled(false);
    btnNext.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNextActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
    jPanel3.add(btnNext, gridBagConstraints);

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setLayout(new java.awt.GridBagLayout());

    jPanel5.setBackground(getBackground());
    jPanel5.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel5.setMinimumSize(new java.awt.Dimension(440, 43));
    jPanel5.setPreferredSize(new java.awt.Dimension(440, 43));

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel2.setText("Endereço");

    txtAddress.setEditable(false);
    txtAddress.setBackground(new java.awt.Color(245, 245, 245));
    txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtAddress.setToolTipText("");
    txtAddress.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtAddress.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAddressActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 330,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE)));
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    jPanel4.add(jPanel5, gridBagConstraints);

    jPanel6.setBackground(getBackground());
    jPanel6.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel6.setMinimumSize(new java.awt.Dimension(440, 43));
    jPanel6.setPreferredSize(new java.awt.Dimension(440, 43));

    jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel7.setText("Bairro");

    txtNeighborhood.setEditable(false);
    txtNeighborhood.setBackground(new java.awt.Color(245, 245, 245));
    txtNeighborhood.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtNeighborhood.setToolTipText("");
    txtNeighborhood.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtNeighborhood.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNeighborhoodActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, 331,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()));
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE)));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    jPanel4.add(jPanel6, gridBagConstraints);

    jPanel8.setBackground(getBackground());
    jPanel8.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel8.setMinimumSize(new java.awt.Dimension(440, 43));
    jPanel8.setPreferredSize(new java.awt.Dimension(435, 43));

    jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel9.setText("Cidade");

    txtState.setEditable(false);
    txtState.setBackground(new java.awt.Color(245, 245, 245));
    txtState.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtState.setToolTipText("");
    txtState.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtState.setMinimumSize(new java.awt.Dimension(64, 100));
    txtState.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtStateActionPerformed(evt);
      }
    });

    jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel10.setText("Estado");

    txtCity.setEditable(false);
    txtCity.setBackground(new java.awt.Color(245, 245, 245));
    txtCity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtCity.setToolTipText("");
    txtCity.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtCity.setMinimumSize(new java.awt.Dimension(64, 100));
    txtCity.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtCityActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE)));
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel4.add(jPanel8, gridBagConstraints);

    jPanel10.setBackground(getBackground());
    jPanel10.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel10.setMinimumSize(new java.awt.Dimension(440, 43));

    jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel12.setText("Celular");

    txtCellphone.setEditable(false);
    txtCellphone.setBackground(new java.awt.Color(245, 245, 245));
    txtCellphone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtCellphone.setToolTipText("");
    txtCellphone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtCellphone.setMinimumSize(new java.awt.Dimension(64, 100));
    txtCellphone.setPreferredSize(new java.awt.Dimension(189, 31));
    txtCellphone.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtCellphoneActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCellphone, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap()));
    jPanel10Layout.setVerticalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCellphone, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    jPanel4.add(jPanel10, gridBagConstraints);

    jPanel9.setBackground(getBackground());
    jPanel9.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel9.setMinimumSize(new java.awt.Dimension(440, 43));
    jPanel9.setPreferredSize(new java.awt.Dimension(440, 43));

    jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel11.setText("Email");

    txtEmail.setEditable(false);
    txtEmail.setBackground(new java.awt.Color(245, 245, 245));
    txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtEmail.setToolTipText("");
    txtEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtEmail.setMinimumSize(new java.awt.Dimension(64, 100));
    txtEmail.setPreferredSize(new java.awt.Dimension(189, 31));
    txtEmail.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtEmailActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap()));
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    jPanel4.add(jPanel9, gridBagConstraints);

    jPanel11.setBackground(getBackground());
    jPanel11.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel11.setMinimumSize(new java.awt.Dimension(440, 43));

    jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel13.setText("CPF");

    txtCpf.setEditable(false);
    txtCpf.setBackground(new java.awt.Color(245, 245, 245));
    txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtCpf.setToolTipText("");
    txtCpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtCpf.setMinimumSize(new java.awt.Dimension(64, 100));
    txtCpf.setPreferredSize(new java.awt.Dimension(189, 31));
    txtCpf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtCpfActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
    jPanel11.setLayout(jPanel11Layout);
    jPanel11Layout.setHorizontalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 365,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel11Layout.setVerticalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    jPanel4.add(jPanel11, gridBagConstraints);

    jPanel7.setBackground(getBackground());
    jPanel7.setLayout(new java.awt.GridBagLayout());

    btnEdit.setBackground(new java.awt.Color(0, 126, 255));
    btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnEdit.setForeground(new java.awt.Color(255, 255, 255));
    btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
    btnEdit.setText("Editar");
    btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });
    jPanel7.add(btnEdit, new java.awt.GridBagConstraints());

    btnDelete.setBackground(new java.awt.Color(234, 45, 67));
    btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnDelete.setForeground(new java.awt.Color(255, 255, 255));
    btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
    btnDelete.setText("Excluir");
    btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });
    jPanel7.add(btnDelete, new java.awt.GridBagConstraints());

    javax.swing.GroupLayout visualizerLayout = new javax.swing.GroupLayout(visualizer);
    visualizer.setLayout(visualizerLayout);
    visualizerLayout.setHorizontalGroup(
        visualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblContactName, javax.swing.GroupLayout.Alignment.TRAILING,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(visualizerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(visualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addGroup(visualizerLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddContact, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    visualizerLayout.setVerticalGroup(
        visualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(visualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(btnAddContact, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContactName)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    getContentPane().add(visualizer, "card2");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void displayContact() {
    lblContactName.setText(selectedContact.getName());
    cmbChangeContact.setSelectedItem(selectedContact.getName());
    txtAddress.setText(selectedContact.getAdress());
    txtNeighborhood.setText(selectedContact.getNeighborhood());
    txtCity.setText(selectedContact.getCity());
    txtState.setText(selectedContact.getState());
    txtCellphone.setText(selectedContact.getPhoneNumber());
    txtEmail.setText(selectedContact.getEmail());
    txtCpf.setText(selectedContact.getCpf());
  }

  private void updateSelectedContact() {
    selectedContact = contacts.get(actualContactIndex);
    displayContact();
  }

  private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed

  }// GEN-LAST:event_jTextField1ActionPerformed

  private void txtNeighborhoodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField6ActionPerformed

  }// GEN-LAST:event_jTextField6ActionPerformed

  private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField8ActionPerformed

  }// GEN-LAST:event_jTextField8ActionPerformed

  private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField9ActionPerformed

  }// GEN-LAST:event_jTextField9ActionPerformed

  private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField11ActionPerformed

  }// GEN-LAST:event_jTextField11ActionPerformed

  private void txtCellphoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField12ActionPerformed

  }// GEN-LAST:event_jTextField12ActionPerformed

  private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField13ActionPerformed

  }// GEN-LAST:event_jTextField13ActionPerformed

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
    this.setVisible(false);
    new EditForm(contacts, selectedContact).setVisible(true);
  }// GEN-LAST:event_btnEditActionPerformed

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
    int option = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o contato?", "Agenda",
        JOptionPane.YES_NO_OPTION);

    if (option != JOptionPane.YES_OPTION)
      return;

    try {
      contactController.deleteContact(selectedContact.getId());
      JOptionPane.showMessageDialog(null, "Contato excluído com sucesso", getTitle(), JOptionPane.INFORMATION_MESSAGE);
      cmbChangeContact.removeItem(selectedContact.getName());

      int deletedContactIndex = FindContact.findIndexOfContactByName(selectedContact.getName(), contacts);

      contacts.remove(deletedContactIndex);
      actualContactIndex = deletedContactIndex != 0 ? deletedContactIndex - 1 : 0;
      updateSelectedContact();
    } catch (Exception e) {
      System.err.println(e);
      JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir o contato", "Erro", JOptionPane.ERROR_MESSAGE);
    }
  }// GEN-LAST:event_btnDeleteActionPerformed

  private void btnAddContactActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddContactFormActionPerformed
    this.setVisible(false);
    new AddContactForm(contacts).setVisible(true);
  }// GEN-LAST:event_btnAddContactFormActionPerformed

  private void cmbChangeContactActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cmbChangeContactActionPerformed
    String name = cmbChangeContact.getSelectedItem().toString();
    actualContactIndex = FindContact.findIndexOfContactByName(name, contacts);
    updateSelectedContact();
  }// GEN-LAST:event_cmbChangeContactActionPerformed

  private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPreviousActionPerformed
    if (actualContactIndex != 0) {
      actualContactIndex--;
      updateSelectedContact();
    }
  }// GEN-LAST:event_btnPreviousActionPerformed

  private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNextActionPerformed
    if (actualContactIndex != contacts.size() - 1) {
      actualContactIndex++;
      updateSelectedContact();
    }
  }// GEN-LAST:event_btnNextActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ContactsNavigator.class.getName()).log(
          java.util.logging.Level.SEVERE,
          null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ContactsNavigator.class.getName()).log(
          java.util.logging.Level.SEVERE,
          null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ContactsNavigator.class.getName()).log(
          java.util.logging.Level.SEVERE,
          null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ContactsNavigator.class.getName()).log(
          java.util.logging.Level.SEVERE,
          null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ContactsNavigator().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAddContact;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton btnNext;
  private javax.swing.JButton btnPrevious;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JComboBox<String> cmbChangeContact;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel10;
  private javax.swing.JPanel jPanel11;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JLabel lblContactImage;
  private javax.swing.JLabel lblContactName;
  private javax.swing.JTextField txtAddress;
  private javax.swing.JTextField txtCellphone;
  private javax.swing.JTextField txtCity;
  private javax.swing.JTextField txtCpf;
  private javax.swing.JTextField txtEmail;
  private javax.swing.JTextField txtNeighborhood;
  private javax.swing.JTextField txtState;
  private javax.swing.JPanel visualizer;
  // End of variables declaration//GEN-END:variables
}
