/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.addform;

import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;

import views.contactsnavigator.ContactsNavigator;
import validation.CpfValidation;
import validation.InputValidation;
import models.Contact;
import controllers.ContactController;

/**
 *
 * @author rafas
 */
public class AddContactForm extends javax.swing.JFrame {
  private List<Contact> contacts;

  /**
   * Creates new form AddContactForm
   */
  public AddContactForm(ArrayList<Contact> contacts) {
    initComponents();
    this.contacts = contacts;
    System.out.println(contacts);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    addForm = new javax.swing.JPanel();
    btnPrevious1 = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jPanel12 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    txtAddName = new javax.swing.JTextField();
    jPanel13 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    txtAddAddress = new javax.swing.JTextField();
    jPanel14 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    txtAddNeighborhood = new javax.swing.JTextField();
    jPanel15 = new javax.swing.JPanel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    txtAddCity = new javax.swing.JTextField();
    cmbAddState = new javax.swing.JComboBox<>();
    jPanel16 = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    txtAddPhone = new javax.swing.JTextField();
    jPanel17 = new javax.swing.JPanel();
    jLabel16 = new javax.swing.JLabel();
    txtAddEmail = new javax.swing.JTextField();
    jPanel18 = new javax.swing.JPanel();
    jLabel17 = new javax.swing.JLabel();
    txtAddCpf = new javax.swing.JTextField();
    btnCreateContact = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    addForm.setBackground(new java.awt.Color(255, 255, 255));

    btnPrevious1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/go-back.png"))); // NOI18N
    btnPrevious1.setBorder(null);
    btnPrevious1.setBorderPainted(false);
    btnPrevious1.setContentAreaFilled(false);
    btnPrevious1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnPrevious1.setName("btnAddContact"); // NOI18N
    btnPrevious1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPrevious1ActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel3.setText("Adicionar contato");

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jPanel12.setBackground(new java.awt.Color(255, 255, 255));
    jPanel12.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel12.setMinimumSize(new java.awt.Dimension(440, 43));

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel4.setText("Nome");

    txtAddName.setBackground(new java.awt.Color(245, 245, 245));
    txtAddName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtAddName.setToolTipText("");
    txtAddName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtAddName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAddNameActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddName,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    330,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE)));
    jPanel12Layout.setVerticalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddName,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE)));

    jPanel13.setBackground(new java.awt.Color(255, 255, 255));
    jPanel13.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel13.setMinimumSize(new java.awt.Dimension(440, 43));

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel5.setText("Endereço");

    txtAddAddress.setBackground(new java.awt.Color(245, 245, 245));
    txtAddAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtAddAddress.setToolTipText("");
    txtAddAddress.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtAddAddress.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAddAddressActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
    jPanel13.setLayout(jPanel13Layout);
    jPanel13Layout.setHorizontalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddAddress,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    317,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE)));
    jPanel13Layout.setVerticalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddAddress,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE)));

    jPanel14.setBackground(new java.awt.Color(255, 255, 255));
    jPanel14.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel14.setMinimumSize(new java.awt.Dimension(440, 43));

    jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel6.setText("Bairro");

    txtAddNeighborhood.setBackground(new java.awt.Color(245, 245, 245));
    txtAddNeighborhood.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtAddNeighborhood.setToolTipText("");
    txtAddNeighborhood.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtAddNeighborhood.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAddNeighborhoodActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
    jPanel14.setLayout(jPanel14Layout);
    jPanel14Layout.setHorizontalGroup(
        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddNeighborhood,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    332,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE)));
    jPanel14Layout.setVerticalGroup(
        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddNeighborhood,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE)));

    jPanel15.setBackground(new java.awt.Color(255, 255, 255));
    jPanel15.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel15.setMinimumSize(new java.awt.Dimension(440, 43));
    jPanel15.setPreferredSize(new java.awt.Dimension(435, 43));

    jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel14.setText("Cidade");

    jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel15.setText("Estado");

    txtAddCity.setBackground(new java.awt.Color(245, 245, 245));
    txtAddCity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtAddCity.setToolTipText("");
    txtAddCity.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtAddCity.setMinimumSize(new java.awt.Dimension(64, 100));
    txtAddCity.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAddCityActionPerformed(evt);
      }
    });

    cmbAddState.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    cmbAddState.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS",
            "MT", "PA", "PB",
            "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP",
            "TO" }));

    javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
    jPanel15.setLayout(jPanel15Layout);
    jPanel15Layout.setHorizontalGroup(
        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddCity,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    168,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAddState,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)));
    jPanel15Layout.setVerticalGroup(
        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAddCity,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cmbAddState))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)));

    jPanel16.setBackground(new java.awt.Color(255, 255, 255));
    jPanel16.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel16.setMinimumSize(new java.awt.Dimension(440, 43));

    jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel8.setText("Celular");

    txtAddPhone.setBackground(new java.awt.Color(245, 245, 245));
    txtAddPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtAddPhone.setToolTipText("");
    txtAddPhone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtAddPhone.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAddPhoneActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
    jPanel16.setLayout(jPanel16Layout);
    jPanel16Layout.setHorizontalGroup(
        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddPhone,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    332,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE)));
    jPanel16Layout.setVerticalGroup(
        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAddPhone,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE)));

    jPanel17.setBackground(new java.awt.Color(255, 255, 255));
    jPanel17.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel17.setMinimumSize(new java.awt.Dimension(440, 43));

    jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel16.setText("Email");

    txtAddEmail.setBackground(new java.awt.Color(245, 245, 245));
    txtAddEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtAddEmail.setToolTipText("");
    txtAddEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtAddEmail.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAddEmailActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddEmail,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    346,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE)));
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtAddEmail,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE)));

    jPanel18.setBackground(new java.awt.Color(255, 255, 255));
    jPanel18.setMaximumSize(new java.awt.Dimension(440, 43));
    jPanel18.setMinimumSize(new java.awt.Dimension(440, 43));

    jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel17.setText("CPF");

    txtAddCpf.setBackground(new java.awt.Color(245, 245, 245));
    txtAddCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txtAddCpf.setText("xxx.xxx.xxx-xx");
    txtAddCpf.setToolTipText("");
    txtAddCpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    txtAddCpf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAddCpfActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
    jPanel18.setLayout(jPanel18Layout);
    jPanel18Layout.setHorizontalGroup(
        jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddCpf,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    358,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)));
    jPanel18Layout.setVerticalGroup(
        jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtAddCpf,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)));

    btnCreateContact.setBackground(new java.awt.Color(0, 255, 72));
    btnCreateContact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnCreateContact.setForeground(new java.awt.Color(255, 255, 255));
    btnCreateContact.setText("Adicionar");
    btnCreateContact.setToolTipText("");
    btnCreateContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnCreateContact.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreateContactActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout
                        .createSequentialGroup()
                        .addGroup(jPanel1Layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel15,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jPanel12,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout
                        .createSequentialGroup()
                        .addGroup(jPanel1Layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel16,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                429,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel17,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCreateContact,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        303,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(78, 78, 78)))
                        .addGap(0, 0, Short.MAX_VALUE)))));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel12,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel17,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnCreateContact)
                .addGap(0, 100, Short.MAX_VALUE)));

    javax.swing.GroupLayout addFormLayout = new javax.swing.GroupLayout(addForm);
    addForm.setLayout(addFormLayout);
    addFormLayout.setHorizontalGroup(
        addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFormLayout
                .createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)
                .addComponent(jLabel3,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    212,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(addFormLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnPrevious1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFormLayout
                .createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)
                .addContainerGap()));
    addFormLayout.setVerticalGroup(
        addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFormLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnPrevious1)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addForm,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addForm,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPrevious1ActionPerformed
    this.setVisible(false);
    new ContactsNavigator().setVisible(true);
  }// GEN-LAST:event_btnPrevious1ActionPerformed

  private void txtAddNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAddNameActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtAddNameActionPerformed

  private void txtAddAddressActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAddAddressActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtAddAddressActionPerformed

  private void txtAddNeighborhoodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAddNeighborhoodActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtAddNeighborhoodActionPerformed

  private void txtAddCityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAddCityActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtAddCityActionPerformed

  private void txtAddPhoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAddPhoneActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtAddPhoneActionPerformed

  private void txtAddEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAddEmailActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtAddEmailActionPerformed

  private void txtAddCpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAddCpfActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtAddCpfActionPerformed

  private void btnCreateContactActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateContactActionPerformed
    String[] inputsValues = {
        txtAddName.getText().trim(),
        txtAddAddress.getText().trim(),
        txtAddNeighborhood.getText().trim(),
        txtAddCity.getText().trim(),
        cmbAddState.getSelectedItem().toString(),
        txtAddPhone.getText().trim(),
        txtAddEmail.getText().trim(),
        txtAddCpf.getText().trim()
    };

    if (!InputValidation.validateInputs(inputsValues))
      return;

    if (InputValidation.nameAlreadyExists(inputsValues[0], contacts))
      return;

    if (InputValidation.cpfAlreadyExists(inputsValues[7], contacts))
      return;

    if (!CpfValidation.isCpfValid(inputsValues[7])) {
      JOptionPane.showMessageDialog(rootPane, "Por favor, insira um CPF válido", "Erro",
          JOptionPane.ERROR_MESSAGE);
      return;
    }

    try {
      ContactController contactController = new ContactController();
      Contact newContact = new Contact(0, inputsValues[0], inputsValues[1], inputsValues[2], inputsValues[3],
          inputsValues[4], inputsValues[5],
          inputsValues[6], inputsValues[7]);

      contactController.addContact(newContact);

      JOptionPane.showMessageDialog(rootPane, "Usuário cadastrado com sucesso", "Sucesso",
          JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
      System.err.println(e);
      JOptionPane.showMessageDialog(null, "Erro ao cadstrar contato", "Erro", JOptionPane.ERROR_MESSAGE);
    } finally {
      this.setVisible(false);
      new ContactsNavigator().setVisible(true);
    }

  }// GEN-LAST:event_btnCreateContactActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AddContactForm.class.getName()).log(
          java.util.logging.Level.SEVERE, null,
          ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AddContactForm.class.getName()).log(
          java.util.logging.Level.SEVERE, null,
          ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AddContactForm.class.getName()).log(
          java.util.logging.Level.SEVERE, null,
          ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AddContactForm.class.getName()).log(
          java.util.logging.Level.SEVERE, null,
          ex);
    }
    // </editor-fold>

    /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new AddContactForm().setVisible(true);
    // }
    // });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel addForm;
  private javax.swing.JButton btnCreateContact;
  private javax.swing.JButton btnPrevious1;
  private javax.swing.JComboBox<String> cmbAddState;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel12;
  private javax.swing.JPanel jPanel13;
  private javax.swing.JPanel jPanel14;
  private javax.swing.JPanel jPanel15;
  private javax.swing.JPanel jPanel16;
  private javax.swing.JPanel jPanel17;
  private javax.swing.JPanel jPanel18;
  private javax.swing.JTextField txtAddAddress;
  private javax.swing.JTextField txtAddCity;
  private javax.swing.JTextField txtAddCpf;
  private javax.swing.JTextField txtAddEmail;
  private javax.swing.JTextField txtAddName;
  private javax.swing.JTextField txtAddNeighborhood;
  private javax.swing.JTextField txtAddPhone;
  // End of variables declaration//GEN-END:variables
}
